#!/bin/bash
#
# SORACOM LTE自動接続スクリプト（本番用）
# WiFi優先、LTE補助のルーティング設定
#

DEVICE_AT="/dev/ttyUSB2"
DEVICE_MBIM="/dev/cdc-wdm0"
IFACE="wwan0"
APN="soracom.io"
LOG_FILE="/var/log/lte_connect.log"
STATE_FILE="/var/run/lte_connected"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [LTE] $1" | tee -a $LOG_FILE
}

# ATコマンド送信（エラーハンドリング付き）
send_at() {
    local cmd="$1"
    local wait_time=${2:-2}

    if [ ! -c "$DEVICE_AT" ]; then
        log_msg "ERROR: $DEVICE_AT not available"
        return 1
    fi

    # stty設定を毎回適用して確実な通信を保証
    stty -F $DEVICE_AT 115200 raw -echo 2>/dev/null || return 1
    echo -e "${cmd}\r" > $DEVICE_AT 2>/dev/null || return 1
    sleep $wait_time
    timeout 3 cat < $DEVICE_AT 2>/dev/null
    return 0
}

# LTE接続処理
lte_connect() {
    log_msg "========================================="
    log_msg "  SORACOM LTE接続開始"
    log_msg "========================================="

    # プロセスクリーンアップ
    log_msg "既存プロセスをクリーンアップ中..."
    pkill -9 mbimcli qmicli 2>/dev/null
    rm -f /tmp/mbim-network-state-* 2>/dev/null
    sleep 1

    # デバイス確認
    if [ ! -c "$DEVICE_AT" ]; then
        log_msg "ERROR: ATデバイスが見つかりません"
        return 1
    fi

    # モデム初期化
    log_msg "モデム初期化中..."
    send_at "ATZ" 2 > /dev/null
    send_at "ATE0" 1 > /dev/null

    # SIM状態確認
    local sim_status=$(send_at "AT+CPIN?" 1)
    if ! echo "$sim_status" | grep -q "READY"; then
        log_msg "ERROR: SIM not ready"
        return 1
    fi
    log_msg "SIM確認: READY"

    # LTEモード確認（既に設定済みのはず）
    local rat_mode=$(send_at "AT!SELRAT?" 1)
    log_msg "RAT Mode: $rat_mode"

    # APN設定
    log_msg "APN設定: $APN"
    send_at "AT+CGDCONT=1,\"IP\",\"${APN}\"" 2 > /dev/null

    # PDP Context有効化
    log_msg "PDP Context有効化中..."
    local cgact_result=$(send_at "AT+CGACT=1,1" 3)

    if echo "$cgact_result" | grep -q "ERROR"; then
        log_msg "WARN: PDP有効化で警告、状態確認中..."
    fi

    # PDP状態確認
    local pdp_status=$(send_at "AT+CGACT?" 2)
    if ! echo "$pdp_status" | grep -q "+CGACT: 1,1"; then
        log_msg "ERROR: PDP Context有効化失敗"
        return 1
    fi
    log_msg "PDP Context: Activated"

    # IP情報取得
    local ip_info=$(send_at "AT+CGCONTRDP=1" 3)
    local ip_addr=$(echo "$ip_info" | grep "+CGCONTRDP:" | awk -F',' '{print $4}' | tr -d '\"' | head -1)
    local dns1=$(echo "$ip_info" | grep "+CGCONTRDP:" | awk -F',' '{print $6}' | tr -d '\"' | head -1)
    local dns2=$(echo "$ip_info" | grep "+CGCONTRDP:" | awk -F',' '{print $7}' | tr -d '\"' | head -1)

    if [ -z "$ip_addr" ] || [ "$ip_addr" = "0.0.0.0" ]; then
        log_msg "ERROR: IPアドレス取得失敗"
        return 1
    fi

    log_msg "IP取得成功: $ip_addr"
    log_msg "DNS: $dns1, $dns2"

    # wwan0インターフェース設定
    log_msg "wwan0設定中..."
    ip link set $IFACE down 2>/dev/null
    ip addr flush dev $IFACE 2>/dev/null
    ip link set $IFACE up
    ip addr add ${ip_addr}/32 dev $IFACE
    ip link set $IFACE mtu 1428

    # ルーティング設定（WiFi優先・LTE補助）
    configure_routing

    # DNS設定
    configure_dns "$dns1" "$dns2"

    # 接続テスト
    if ping -c 2 -W 3 -I $IFACE 8.8.8.8 >/dev/null 2>&1; then
        log_msg "SUCCESS: LTE接続確立完了"
        touch $STATE_FILE
        return 0
    else
        log_msg "WARN: Ping失敗（ルーティング確認推奨）"
        touch $STATE_FILE
        return 0
    fi
}

# ルーティング設定
configure_routing() {
    log_msg "ルーティング設定中..."

    # 既存のwwan0ルート削除
    ip route del default dev $IFACE 2>/dev/null

    # WiFi状態確認
    local wifi_state=$(cat /sys/class/net/wlan0/operstate 2>/dev/null)

    if [ "$wifi_state" = "up" ] && ip addr show wlan0 2>/dev/null | grep -q "inet "; then
        # WiFi接続中: WiFi優先（metric 100）、LTE補助（metric 400）
        log_msg "WiFi接続中 - WiFi優先ルート設定"

        # WiFi優先ルート確認・設定
        if ! ip route | grep -q "default.*wlan0.*metric 100"; then
            local wifi_gw=$(ip route | grep "^default.*wlan0" | awk '{print $3}' | head -1)
            if [ -z "$wifi_gw" ]; then
                wifi_gw="192.168.3.1"
            fi
            ip route add default via $wifi_gw dev wlan0 metric 100 2>/dev/null
            log_msg "WiFiルート追加: via $wifi_gw metric 100"
        fi

        # LTE補助ルート
        ip route add default dev $IFACE metric 400 2>/dev/null
        log_msg "LTEルート追加: dev $IFACE metric 400"

    else
        # WiFi未接続: LTE専用（metric 200）
        log_msg "WiFi未接続 - LTE専用ルート設定"
        ip route add default dev $IFACE metric 200
        log_msg "LTEルート追加: dev $IFACE metric 200"
    fi

    log_msg "現在のルート:"
    ip route show | tee -a $LOG_FILE
}

# DNS設定
configure_dns() {
    local dns1=$1
    local dns2=$2

    if [ -n "$dns1" ] && [ "$dns1" != "0.0.0.0" ]; then
        cat > /etc/resolv.conf << EOF
# Generated by lte_soracom_connect.sh
nameserver ${dns1}
nameserver 8.8.8.8
EOF
        [ -n "$dns2" ] && [ "$dns2" != "0.0.0.0" ] && echo "nameserver ${dns2}" >> /etc/resolv.conf
        log_msg "DNS設定完了: $dns1"
    fi
}

# LTE切断処理
lte_disconnect() {
    log_msg "========================================="
    log_msg "  LTE切断開始"
    log_msg "========================================="

    # PDP Context無効化
    send_at "AT+CGACT=0,1" 2 > /dev/null

    # インターフェースダウン
    ip route del default dev $IFACE 2>/dev/null
    ip addr flush dev $IFACE 2>/dev/null
    ip link set $IFACE down 2>/dev/null

    rm -f $STATE_FILE
    log_msg "LTE切断完了"
}

# 状態確認
lte_status() {
    if [ -f $STATE_FILE ]; then
        echo "LTE Status: Connected"
        ip addr show $IFACE 2>/dev/null
        ip route show | grep $IFACE
    else
        echo "LTE Status: Disconnected"
    fi
}

# メイン処理
case "$1" in
    connect)
        lte_connect
        exit $?
        ;;
    disconnect)
        lte_disconnect
        exit $?
        ;;
    status)
        lte_status
        exit $?
        ;;
    *)
        echo "Usage: $0 {connect|disconnect|status}"
        exit 1
        ;;
esac
