#!/bin/bash
#
# QMI専用 SORACOM接続スクリプト
# cdc_mbimドライバーを無効化してqmi_wwanのみで接続
#

DEVICE_QMI="/dev/cdc-wdm0"
IFACE="wwan0"
APN="soracom.io"
LOG_FILE="/var/log/qmi_soracom.log"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [QMI_ONLY] $1" | tee -a $LOG_FILE
}

log_msg "==========================================="
log_msg "  QMI専用 SORACOM LTE接続"
log_msg "==========================================="

# ステップ1: cdc_mbimドライバーをアンロード
log_msg "=== STEP 1: cdc_mbimドライバー無効化 ==="
if lsmod | grep -q cdc_mbim; then
    log_msg "cdc_mbimドライバーをアンロード中..."
    rmmod cdc_mbim 2>/dev/null
    sleep 2

    if lsmod | grep -q cdc_mbim; then
        log_msg "ERROR: cdc_mbimアンロード失敗"
    else
        log_msg "✓ cdc_mbimアンロード成功"
    fi
fi

# qmi_wwanドライバー確認
if lsmod | grep -q qmi_wwan; then
    log_msg "✓ qmi_wwanドライバー: ロード済み"
else
    log_msg "qmi_wwanドライバーをロード中..."
    modprobe qmi_wwan
    sleep 2
fi

# ステップ2: プロセスクリーンアップ
log_msg "=== STEP 2: プロセスクリーンアップ ==="
pkill -9 qmicli mbimcli 2>/dev/null
rm -f /tmp/qmi-network-state-* 2>/dev/null
sleep 2

# ステップ3: デバイス確認
log_msg "=== STEP 3: デバイス確認 ==="
if [ ! -c "$DEVICE_QMI" ]; then
    log_msg "ERROR: $DEVICE_QMI が見つかりません"
    log_msg "利用可能なデバイス:"
    ls -la /dev/cdc-wdm* 2>&1 | tee -a $LOG_FILE
    exit 1
fi
log_msg "✓ QMIデバイス確認: $DEVICE_QMI"

# ステップ4: インターフェースクリーンアップ
log_msg "=== STEP 4: インターフェース初期化 ==="
ip link set $IFACE down 2>/dev/null
ip addr flush dev $IFACE 2>/dev/null
sleep 1

# ステップ5: QMI接続開始
log_msg "=== STEP 5: QMI接続開始 ==="
log_msg "APN: $APN"

# WDS (Wireless Data Service) セッション開始
log_msg "WDSセッション開始中..."
QMI_RESULT=$(qmicli -d $DEVICE_QMI --wds-start-network="apn='$APN',ip-type=4" --client-no-release-cid 2>&1)
QMI_STATUS=$?

echo "$QMI_RESULT" | while IFS= read -r line; do
    log_msg "  $line"
done

if [ $QMI_STATUS -ne 0 ]; then
    log_msg "ERROR: QMI WDS接続失敗"
    exit 1
fi

# Packet Data Handle (PDH) 取得
PDH=$(echo "$QMI_RESULT" | grep "Packet data handle" | awk -F"'" '{print $2}')
if [ -z "$PDH" ]; then
    log_msg "WARN: PDH未取得、継続..."
else
    log_msg "✓ PDH取得: $PDH"
    echo "$PDH" > /var/run/qmi_pdh
fi

sleep 3

# ステップ6: IP設定取得
log_msg "=== STEP 6: IP設定取得 ==="
IP_CONFIG=$(qmicli -d $DEVICE_QMI --wds-get-current-settings 2>&1)
log_msg "IP設定:"
echo "$IP_CONFIG" | while IFS= read -r line; do
    log_msg "  $line"
done

# IP抽出
IP_ADDR=$(echo "$IP_CONFIG" | grep "IPv4 address" | awk -F: '{print $2}' | tr -d ' ')
GATEWAY=$(echo "$IP_CONFIG" | grep "IPv4 gateway address" | awk -F: '{print $2}' | tr -d ' ')
SUBNET=$(echo "$IP_CONFIG" | grep "IPv4 subnet mask" | awk -F: '{print $2}' | tr -d ' ')
DNS1=$(echo "$IP_CONFIG" | grep "IPv4 primary DNS" | awk -F: '{print $2}' | tr -d ' ')
DNS2=$(echo "$IP_CONFIG" | grep "IPv4 secondary DNS" | awk -F: '{print $2}' | tr -d ' ')

if [ -z "$IP_ADDR" ] || [ "$IP_ADDR" = "0.0.0.0" ]; then
    log_msg "ERROR: IPアドレス取得失敗"
    exit 1
fi

log_msg "取得IP: $IP_ADDR"
log_msg "GW: $GATEWAY"
log_msg "DNS1: $DNS1"
log_msg "DNS2: $DNS2"

# ステップ7: インターフェース設定
log_msg "=== STEP 7: インターフェース設定 ==="

# raw-ip モード有効化（重要！）
log_msg "raw-ipモード設定中..."
ip link set dev $IFACE down
echo Y > /sys/class/net/$IFACE/qmi/raw_ip 2>/dev/null
ip link set dev $IFACE up

# IP設定適用
ip addr add ${IP_ADDR}/32 dev $IFACE
ip link set $IFACE mtu 1428

log_msg "✓ $IFACE設定完了: $IP_ADDR/32"

# ステップ8: ルーティング設定
log_msg "=== STEP 8: ルーティング設定 ==="

# WiFi状態確認
WIFI_STATE=$(cat /sys/class/net/wlan0/operstate 2>/dev/null)

if [ "$WIFI_STATE" = "up" ] && ip addr show wlan0 2>/dev/null | grep -q "inet "; then
    log_msg "WiFi接続中 - WiFi優先ルート設定"

    WIFI_GW=$(ip route | grep "^default.*wlan0" | awk '{print $3}' | head -1)
    [ -z "$WIFI_GW" ] && WIFI_GW="192.168.3.1"

    ip route del default dev wlan0 2>/dev/null
    ip route add default via $WIFI_GW dev wlan0 metric 100 2>/dev/null
    log_msg "  WiFiルート: via $WIFI_GW metric 100"

    ip route add default dev $IFACE metric 400 2>/dev/null
    log_msg "  LTEルート: dev $IFACE metric 400"
else
    log_msg "WiFi未接続 - LTE専用ルート"
    ip route add default dev $IFACE metric 200
    log_msg "  LTEルート: dev $IFACE metric 200"
fi

log_msg "現在のルート:"
ip route show | tee -a $LOG_FILE

# ステップ9: DNS設定
log_msg "=== STEP 9: DNS設定 ==="
{
    echo "# Generated by qmi_only_soracom_connect.sh"
    [ -n "$DNS1" ] && [ "$DNS1" != "0.0.0.0" ] && echo "nameserver $DNS1"
    echo "nameserver 8.8.8.8"
    [ -n "$DNS2" ] && [ "$DNS2" != "0.0.0.0" ] && [ "$DNS2" != "$DNS1" ] && echo "nameserver $DNS2"
} > /etc/resolv.conf
log_msg "✓ DNS設定完了"

# ステップ10: 接続テスト
log_msg "=== STEP 10: 接続テスト ==="

log_msg "インターフェース状態:"
ip addr show $IFACE | tee -a $LOG_FILE

log_msg "Pingテスト (wwan0経由)..."
if ping -c 3 -W 5 -I $IFACE 8.8.8.8 >/dev/null 2>&1; then
    log_msg "==========================================="
    log_msg "  ✓✓✓ SUCCESS!!! QMI接続成功！"
    log_msg "==========================================="
    touch /var/run/qmi_connected
    exit 0
else
    log_msg "WARN: Ping失敗 - しかし設定は完了"
    touch /var/run/qmi_connected
    exit 0
fi
