#!/bin/bash
#
# SORACOM IP設定スクリプト (ATコマンド方式)
# MBIMではなくATコマンドでPDP Context初期化・IP設定を行う
#

# 環境変数設定
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# 設定
SERIAL_PORT="/dev/ttyUSB2"
IFACE="wwan0"
LOGFILE="/var/log/soracom-ip-setup.log"
APN="soracom.io"

# ログ関数
log_msg() {
    local level="$1"
    shift
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [$level] $*" | tee -a "$LOGFILE"
}

log_msg "INFO" "=== SORACOM IP設定開始 (ATコマンド方式) ==="

# シリアルポート存在確認
if [ ! -c "$SERIAL_PORT" ]; then
    log_msg "ERROR" "シリアルポート $SERIAL_PORT が見つかりません"
    exit 1
fi

log_msg "INFO" "シリアルポート確認完了: $SERIAL_PORT"

# シリアルポート設定
stty -F $SERIAL_PORT 115200 raw -echo -echoe -echok 2>/dev/null || true

# ATコマンド送信関数
send_at_command() {
    local cmd="$1"
    local description="$2"
    local timeout="${3:-3}"

    log_msg "INFO" "ATコマンド送信: $cmd ($description)"

    # コマンド送信
    echo -e "${cmd}\r" > $SERIAL_PORT

    # 応答読み取り
    local response=""
    local count=0
    while [ $count -lt $timeout ]; do
        if read -t 1 line < $SERIAL_PORT 2>/dev/null; then
            response="${response}${line}"
            # OKまたはERRORが含まれていたら終了
            if echo "$response" | grep -q "OK\|ERROR"; then
                break
            fi
        fi
        count=$((count + 1))
    done

    # 応答ログ出力
    log_msg "DEBUG" "応答: $(echo "$response" | tr -d '\r\n' | head -c 200)"

    # エラーチェック
    if echo "$response" | grep -qi "ERROR"; then
        log_msg "ERROR" "ATコマンドエラー: $cmd"
        return 1
    fi

    # 応答を返す
    echo "$response"
    return 0
}

# === STEP 1: PDP Context初期化 ===
log_msg "INFO" "=== STEP 1: PDP Context初期化 ==="

# APN設定
if ! send_at_command "AT+CGDCONT=1,\"IP\",\"$APN\"" "APN設定" 3 >/dev/null; then
    log_msg "ERROR" "APN設定失敗"
    exit 1
fi
sleep 1

log_msg "INFO" "APN設定完了: $APN"

# PS Service Attach
if ! send_at_command "AT+CGATT=1" "PS Service Attach" 5 >/dev/null; then
    log_msg "ERROR" "PS Service Attach失敗"
    exit 1
fi
sleep 2

log_msg "INFO" "PS Service Attach完了"

# PDP Context Activation
if ! send_at_command "AT+CGACT=1,1" "PDP Context Activation" 8 >/dev/null; then
    log_msg "ERROR" "PDP Context Activation失敗"
    exit 1
fi
sleep 5  # IP割り当て待機時間を延長

log_msg "INFO" "PDP Context Activation完了"

# === STEP 2: IPアドレス取得 ===
log_msg "INFO" "=== STEP 2: IPアドレス取得 ==="

# AT+CGPADDR=1でIPアドレス取得（最大3回リトライ）
ip_response=""
for retry in {1..3}; do
    log_msg "INFO" "IPアドレス取得試行 ($retry/3)..."
    ip_response=$(send_at_command "AT+CGPADDR=1" "IP取得" 3)
    if [ $? -eq 0 ] && echo "$ip_response" | grep -q "+CGPADDR:.*,[0-9]"; then
        break
    fi
    log_msg "WARN" "IPアドレス未割り当て、3秒待機後リトライ..."
    sleep 3
done
if [ $? -ne 0 ]; then
    log_msg "ERROR" "IPアドレス取得失敗"
    exit 1
fi

# IPアドレス抽出
# 応答例: +CGPADDR: 1,10.236.152.129
IP_ADDR=$(echo "$ip_response" | grep -oP '\+CGPADDR:\s*1,\K[0-9.]+' | head -1)

if [ -z "$IP_ADDR" ]; then
    log_msg "ERROR" "IPアドレス抽出失敗 (応答: $ip_response)"
    exit 1
fi

log_msg "INFO" "取得IPアドレス: $IP_ADDR"

# DNS情報取得（オプション）
# AT+CGCONTRDP=1 でDNS情報も取得
dns_response=$(send_at_command "AT+CGCONTRDP=1" "詳細情報取得" 3)
DNS1=$(echo "$dns_response" | grep -oP '\+CGCONTRDP:.*?,.*?,.*?,.*?,.*?,\K[0-9.]+' | head -1)
DNS2=$(echo "$dns_response" | grep -oP '\+CGCONTRDP:.*?,.*?,.*?,.*?,.*?,[^,]+,\K[0-9.]+' | head -1)

if [ -n "$DNS1" ]; then
    log_msg "INFO" "取得DNS1: $DNS1"
fi
if [ -n "$DNS2" ]; then
    log_msg "INFO" "取得DNS2: $DNS2"
fi

# === STEP 3: ネットワーク設定 ===
log_msg "INFO" "=== STEP 3: ネットワーク設定 ==="

# wwan0インターフェース存在確認
if [ ! -e /sys/class/net/$IFACE ]; then
    log_msg "ERROR" "ネットワークインターフェース $IFACE が見つかりません"
    exit 1
fi

# インターフェースUP
log_msg "INFO" "インターフェース $IFACE を起動中..."
ip link set $IFACE up

if [ $? -ne 0 ]; then
    log_msg "ERROR" "インターフェース起動失敗"
    exit 1
fi

# 既存IPアドレス削除（冪等性確保）
log_msg "INFO" "既存IPアドレスをクリア..."
ip addr flush dev $IFACE 2>/dev/null

# IPアドレス設定 (/32 Point-to-Point)
log_msg "INFO" "IPアドレス設定: ${IP_ADDR}/32"
ip addr add ${IP_ADDR}/32 dev $IFACE

if [ $? -ne 0 ]; then
    log_msg "ERROR" "IPアドレス設定失敗"
    exit 1
fi

# MTU設定 (LTE最適値)
log_msg "INFO" "MTU設定: 1428"
ip link set $IFACE mtu 1428

if [ $? -ne 0 ]; then
    log_msg "WARN" "MTU設定失敗（継続）"
fi

# 既存デフォルトルート削除（wwan0関連のみ）
log_msg "INFO" "既存wwan0ルート削除..."
ip route del default dev $IFACE 2>/dev/null

# デフォルトルート追加
log_msg "INFO" "デフォルトルート追加: dev $IFACE"
ip route add default dev $IFACE

if [ $? -ne 0 ]; then
    log_msg "WARN" "デフォルトルート追加失敗（既存ルートがある可能性）"
    # metric指定で再試行
    ip route add default dev $IFACE metric 200 2>/dev/null
fi

# === STEP 4: DNS設定 ===
log_msg "INFO" "=== STEP 4: DNS設定 ==="

# resolv.confのロック解除（存在する場合）
chattr -i /etc/resolv.conf 2>/dev/null

# DNS設定
log_msg "INFO" "DNS設定を書き込み中..."
{
    echo "# Generated by soracom-ip-setup.sh (AT mode)"
    echo "# $(date '+%Y-%m-%d %H:%M:%S')"

    # SORACOM DNS（優先）
    if [ -n "$DNS1" ]; then
        echo "nameserver $DNS1"
    else
        echo "nameserver 100.127.0.53"  # SORACOM DNS1
    fi

    # Google DNS（フォールバック）
    echo "nameserver 8.8.8.8"

    # SORACOM DNS2（オプション）
    if [ -n "$DNS2" ] && [ "$DNS2" != "$DNS1" ]; then
        echo "nameserver $DNS2"
    fi

    # Cloudflare DNS（追加フォールバック）
    echo "nameserver 1.1.1.1"

    # DNS最適化オプション
    echo "options timeout:2"
    echo "options attempts:2"
    echo "options rotate"
} > /etc/resolv.conf

log_msg "INFO" "DNS設定完了"

# === STEP 5: 接続確認 ===
log_msg "INFO" "=== STEP 5: 接続確認 ==="

# インターフェース状態確認
IFACE_STATE=$(ip addr show $IFACE 2>/dev/null | grep "state" | awk '{print $9}')
log_msg "INFO" "インターフェース状態: $IFACE_STATE"

# IPアドレス確認
CONFIGURED_IP=$(ip addr show $IFACE | grep "inet " | awk '{print $2}')
log_msg "INFO" "設定済みIP: $CONFIGURED_IP"

# ルーティング確認
DEFAULT_ROUTE=$(ip route show default | grep $IFACE)
if [ -n "$DEFAULT_ROUTE" ]; then
    log_msg "INFO" "デフォルトルート確認: $DEFAULT_ROUTE"
else
    log_msg "WARN" "デフォルトルートが見つかりません"
fi

# Ping接続テスト（オプション、タイムアウト短め）
log_msg "INFO" "接続テスト実行中 (ping 8.8.8.8)..."
if ping -c 2 -W 3 -I $IFACE 8.8.8.8 >/dev/null 2>&1; then
    log_msg "INFO" "接続テスト成功: LTE経由でインターネット到達可能"
    CONNECTIVITY_STATUS="SUCCESS"
else
    log_msg "WARN" "接続テスト失敗 (タイムアウト)"
    CONNECTIVITY_STATUS="TIMEOUT"
fi

# === 完了サマリー ===
log_msg "INFO" "=== 設定完了サマリー ==="
log_msg "INFO" "  IPアドレス: $IP_ADDR"
log_msg "INFO" "  インターフェース: $IFACE"
log_msg "INFO" "  MTU: 1428"
log_msg "INFO" "  DNS1: ${DNS1:-100.127.0.53}"
log_msg "INFO" "  DNS2: 8.8.8.8"
log_msg "INFO" "  接続状態: $CONNECTIVITY_STATUS"
log_msg "INFO" "=== SORACOM IP設定完了 ==="

exit 0
