#!/bin/bash
#
# SORACOM IP設定スクリプト (MBIM専用版)
# mbim-network接続後のIP/ルーティング設定
#

# 環境変数設定
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

DEV="/dev/cdc-wdm0"
IFACE="wwan0"
LOGFILE="/var/log/soracom-ip-setup.log"

# ログ関数
log_msg() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOGFILE"
}

log_msg "=== soracom-ip-setup.sh started ==="

# MBIM接続確認
log_msg "MBIM接続状態確認中..."
CONN_STATE=$(mbimcli -d $DEV --query-connection-state 2>&1)

if ! echo "$CONN_STATE" | grep -q "Activation state: 'activated'"; then
    log_msg "ERROR: MBIM接続が確立されていません"
    log_msg "Connection state: $CONN_STATE"
    exit 1
fi

log_msg "MBIM接続確認: activated"

# IP設定取得 (MBIM経由)
log_msg "IP設定取得中 (mbimcli)..."
IP_CONFIG=$(mbimcli -d $DEV --query-ip-configuration 2>&1)

if echo "$IP_CONFIG" | grep -qi "error\|ContextNotActivated"; then
    log_msg "ERROR: IP設定取得失敗"
    log_msg "$IP_CONFIG"
    exit 1
fi

# IPv4アドレス抽出
IPV4_ADDR=$(echo "$IP_CONFIG" | grep -oP "IP \[0\]:\s*'\K[^']*" | head -1)
IPV4_PREFIX=$(echo "$IP_CONFIG" | grep -oP "Prefix:\s*'\K[^']*" | head -1)
IPV4_GATEWAY=$(echo "$IP_CONFIG" | grep -oP "Gateway:\s*'\K[^']*" | head -1)
IPV4_DNS1=$(echo "$IP_CONFIG" | grep -oP "DNS \[0\]:\s*'\K[^']*" | head -1)
IPV4_DNS2=$(echo "$IP_CONFIG" | grep -oP "DNS \[1\]:\s*'\K[^']*" | head -1)
IPV4_MTU=$(echo "$IP_CONFIG" | grep -oP "MTU:\s*'\K[^']*" | head -1)

log_msg "取得したIP情報:"
log_msg "  IP Address: $IPV4_ADDR/$IPV4_PREFIX"
log_msg "  Gateway: $IPV4_GATEWAY"
log_msg "  DNS1: $IPV4_DNS1"
log_msg "  DNS2: $IPV4_DNS2"
log_msg "  MTU: $IPV4_MTU"

# IP設定チェック
if [ -z "$IPV4_ADDR" ]; then
    log_msg "ERROR: IPアドレスが取得できませんでした"
    exit 1
fi

# インターフェースUP
log_msg "インターフェース $IFACE を起動中..."
ip link set $IFACE up

# 既存IP削除
ip addr flush dev $IFACE 2>/dev/null

# IPアドレス設定
if [ -n "$IPV4_PREFIX" ]; then
    IP_WITH_PREFIX="${IPV4_ADDR}/${IPV4_PREFIX}"
else
    # デフォルトはPoint-to-Point (/32)
    IP_WITH_PREFIX="${IPV4_ADDR}/32"
fi

log_msg "IPアドレス設定: $IP_WITH_PREFIX"
ip addr add $IP_WITH_PREFIX dev $IFACE

if [ $? -ne 0 ]; then
    log_msg "ERROR: IPアドレス設定失敗"
    exit 1
fi

# MTU設定
if [ -n "$IPV4_MTU" ] && [ "$IPV4_MTU" != "0" ]; then
    log_msg "MTU設定: $IPV4_MTU"
    ip link set dev $IFACE mtu $IPV4_MTU
else
    # LTE最適MTU
    log_msg "MTU設定: 1428 (LTE最適値)"
    ip link set dev $IFACE mtu 1428
fi

# デフォルトルート設定
log_msg "デフォルトルート設定中..."
ip route del default dev $IFACE 2>/dev/null

if [ -n "$IPV4_GATEWAY" ] && [ "$IPV4_GATEWAY" != "0.0.0.0" ]; then
    # ゲートウェイ指定あり
    log_msg "ルート設定 (with gateway): via $IPV4_GATEWAY dev $IFACE metric 200"
    ip route add default via $IPV4_GATEWAY dev $IFACE metric 200
else
    # Point-to-Point (SORACOM標準)
    log_msg "ルート設定 (Point-to-Point): dev $IFACE metric 200"
    ip route add default dev $IFACE metric 200
fi

if [ $? -ne 0 ]; then
    log_msg "WARN: デフォルトルート設定失敗"
fi

# DNS設定
log_msg "DNS設定中..."

# 既存のロック解除
chattr -i /etc/resolv.conf 2>/dev/null

# DNS優先順位: パブリックDNS > キャリアDNS
{
    echo "# Generated by soracom-ip-setup.sh"
    echo "nameserver 8.8.8.8"          # Google DNS (最優先)
    echo "nameserver 1.1.1.1"          # Cloudflare DNS

    # キャリアDNS追加
    [ -n "$IPV4_DNS1" ] && [ "$IPV4_DNS1" != "0.0.0.0" ] && echo "nameserver $IPV4_DNS1"
    [ -n "$IPV4_DNS2" ] && [ "$IPV4_DNS2" != "0.0.0.0" ] && echo "nameserver $IPV4_DNS2"

    # DNS最適化オプション
    echo "options timeout:2"
    echo "options attempts:2"
    echo "options rotate"
} > /etc/resolv.conf

log_msg "DNS設定完了: 8.8.8.8, 1.1.1.1, $IPV4_DNS1, $IPV4_DNS2"

# 接続確認
log_msg "接続テスト実行中..."
if ping -c 1 -W 3 -I $IFACE 8.8.8.8 >/dev/null 2>&1; then
    log_msg "接続テスト成功: LTE経由でインターネット到達可能"
else
    log_msg "WARN: 接続テスト失敗: ping 8.8.8.8 タイムアウト"
fi

log_msg "=== soracom-ip-setup.sh completed successfully ==="
exit 0
