; FoxSense 子機ファームウェア (LoRa版)
; Seeed XIAO ESP32-C3 + ES920LR3(LoRa/技適) + FS304-SHT3x(防水温湿度)
[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
lib_deps =
    adafruit/Adafruit SHT31 Library@^2.2.2
    adafruit/Adafruit Unified Sensor@^1.1.9
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
